=== cappuccinocosmico/config/WarpDrive/WarpDrive.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" targetNamespace="WarpDrive" xmlns="WarpDrive" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:complexType name="forElement">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="for" type="forElement" maxOccurs="unbounded" minOccurs="0" />
			<xs:element name="fillerSet" type="fillerSetElement" maxOccurs="unbounded" minOccurs="0" />
			<xs:element name="import" type="importElement" maxOccurs="unbounded" minOccurs="0" />
			<xs:element name="filler" type="fillerElement" maxOccurs="unbounded" minOccurs="0" />
			<xs:element name="structure" type="structureElement" maxOccurs="unbounded" minOccurs="0" />
			<xs:element name="metashell" type="metashellElement" maxOccurs="unbounded" minOccurs="0" />
			<xs:element name="shell" type="shellElement" maxOccurs="unbounded" minOccurs="0" />
		</xs:choice>
		<xs:attribute type="xs:string" name="variable" use="required" />
		<xs:attribute type="xs:string" name="from" use="optional" />
		<xs:attribute type="xs:string" name="to" use="optional" />
		<xs:attribute type="xs:string" name="in" use="optional" />
		<xs:attribute type="xs:string" name="mods" use="optional" />
	</xs:complexType>

	<xs:complexType name="fillerSetElement">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="for" type="forElement" maxOccurs="unbounded" minOccurs="0" />
			<xs:element name="import" type="importElement" maxOccurs="unbounded" minOccurs="0" />
			<xs:element name="filler" type="fillerElement" maxOccurs="unbounded" minOccurs="0" />
		</xs:choice>
		<xs:attribute type="xs:string" name="group" use="required" />
		<xs:attribute type="xs:string" name="name" use="required" />
		<xs:attribute type="xs:string" name="weight" use="optional" />
		<xs:attribute type="xs:string" name="ratio" use="optional" />
		<xs:attribute type="xs:string" name="mods" use="optional" />
	</xs:complexType>

	<xs:complexType name="importElement">
		<xs:attribute type="xs:string" name="group" use="required" />
		<xs:attribute type="xs:string" name="name" use="optional" />
		<xs:attribute type="xs:string" name="mods" use="optional" />
	</xs:complexType>

	<xs:complexType name="fillerElement">
		<xs:attribute type="xs:string" name="block" use="required" />
		<xs:attribute type="xs:string" name="metadata" use="optional" />
		<xs:attribute type="xs:string" name="weight" use="optional" />
		<xs:attribute type="xs:string" name="ratio" use="optional" />
		<xs:attribute type="xs:string" name="mods" use="optional" />
	</xs:complexType>

	<xs:complexType name="structureElement">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="for" type="forElement" maxOccurs="unbounded" minOccurs="0" />
			<xs:element name="import" type="importElement" maxOccurs="unbounded" minOccurs="0" />
            <xs:element name="schematic" type="schematicElement" maxOccurs="1" minOccurs="0" />
			<xs:element name="metashell" type="metashellElement" maxOccurs="1" minOccurs="0" />
			<xs:element name="shell" type="shellElement" maxOccurs="unbounded" minOccurs="0" />
		</xs:choice>
		<xs:attribute type="xs:string" name="group" use="required" />
		<xs:attribute type="xs:string" name="name" use="required" />
		<xs:attribute type="xs:string" name="weight" use="optional" />
		<xs:attribute type="xs:string" name="ratio" use="optional" />
		<xs:attribute type="xs:string" name="mods" use="optional" />
	</xs:complexType>

    <xs:complexType name="schematicElement">
        <xs:attribute type="xs:string" name="group" use="required" />
        <xs:attribute type="xs:string" name="name" use="optional" />
        <xs:attribute type="xs:string" name="mods" use="optional" />
    </xs:complexType>

	<xs:complexType name="metashellElement">
		<xs:attribute type="xs:string" name="block" use="optional" />
		<xs:attribute type="xs:string" name="metadata" use="optional" />
		<xs:attribute type="xs:string" name="minCount" use="required" />
		<xs:attribute type="xs:string" name="maxCount" use="required" />
		<xs:attribute type="xs:string" name="minRadius" use="required" />
		<xs:attribute type="xs:string" name="relativeRadius" use="required" />
		<xs:attribute type="xs:string" name="mods" use="optional" />
	</xs:complexType>

	<xs:complexType name="shellElement">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="for" type="forElement" maxOccurs="unbounded" minOccurs="0" />
			<xs:element name="import" type="importElement" maxOccurs="unbounded" minOccurs="0" />
			<xs:element name="filler" type="fillerElement" maxOccurs="unbounded" minOccurs="0" />
		</xs:choice>
		<xs:attribute type="xs:string" name="name" use="required" />
		<xs:attribute type="xs:string" name="minThickness" use="required" />
		<xs:attribute type="xs:string" name="maxThickness" use="required" />
		<xs:attribute type="xs:string" name="mods" use="optional" />
	</xs:complexType>

	<xs:element name="worldGeneration">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element name="for" type="forElement" maxOccurs="unbounded" minOccurs="0" />
				<xs:element name="fillerSet" type="fillerSetElement" maxOccurs="unbounded" minOccurs="0" />
				<xs:element name="structure" type="structureElement" maxOccurs="unbounded" minOccurs="0" />
			</xs:choice>
			<xs:attribute type="xs:string" name="version" use="required" />
			<xs:attribute type="xs:string" name="mods" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== cappuccinocosmico/config/WarpDrive/filler-default.xml
<?xml version="1.0" encoding="utf-8"?>

<worldGeneration version="2" xmlns="WarpDrive" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="WarpDrive warpDrive.xsd">

	<!-- all possible overworld ores, mostly for reference purpose -->
	<fillerSet group="overworld_allOres" name="stone">
		<import group="overworld_commonOres" name="stone" />
		<import group="overworld_uncommonOres" name="stone" />
		<import group="overworld_rareOres" name="stone" />
	</fillerSet>

	<!-- common overworld ores with various base blocks -->
	<fillerSet group="overworld_common" name="stone" weight="20">
		<import group="overworld_commonOres" name="stone" />
		<filler block="minecraft:stone" weight="1" />
	</fillerSet>
	<fillerSet group="overworld_common" name="corrupted" weight="5">
		<import group="overworld_commonOres" name="stone" />
		<filler block="minecraft:stone" weight="5" />
		<filler block="minecraft:cobblestone" weight="1" />
	</fillerSet>
	<fillerSet group="overworld_common" name="cobblestone" weight="1">
		<import group="overworld_commonOres" name="stone" />
		<filler block="minecraft:cobblestone" weight="1" />
	</fillerSet>
	<fillerSet group="overworld_common" name="sandNclay" weight="2">
		<import group="overworld_commonOres" name="stone" />
		<filler block="minecraft:sandstone" weight="1" />
		<filler block="minecraft:clay" weight="1" />
	</fillerSet>

	<fillerSet group="overworld_commonOres" name="stone">
		<import group="overworld_commonOres" name="allButVanilla" />
		<filler block="minecraft:coal_ore" ratio=".08" />
		<filler block="minecraft:iron_ore" ratio=".05" />
		<filler block="minecraft:redstone_ore" ratio=".02" />
	</fillerSet>
	<fillerSet group="overworld_commonOres" name="allButVanilla">
		<filler block="IC2:blockOreTin" ratio=".05" mods="IC2,!ImmersiveEngineering" />
		<filler block="IC2:blockOreCopper" ratio=".06" mods="IC2,!ImmersiveEngineering" />
		<filler block="IC2:blockOreLead" ratio=".06" mods="IC2,!ImmersiveEngineering" />
		<filler block="ImmersiveEngineering:ore" metadata="0" ratio=".05" mods="ImmersiveEngineering" /><!-- Copper -->
		<filler block="ImmersiveEngineering:ore" metadata="1" ratio=".06" mods="ImmersiveEngineering" /><!-- Bauxite -->
		<filler block="ImmersiveEngineering:ore" metadata="2" ratio=".06" mods="ImmersiveEngineering" /><!-- Lead -->
		<filler block="arsmagica2:vinteumOre" metadata="0" ratio=".001" mods="arsmagica2" /><!-- Vinteum -->
		<filler block="icbm:sulfur_ore" ratio=".001" /><!-- to be confirmed -->
	</fillerSet>


	<!-- uncommon overworld ores with various base blocks -->
	<fillerSet group="overworld_uncommon" name="stone" weight="10">
		<import group="overworld_uncommonOres" name="stone" />
		<filler block="minecraft:stone" weight="1" />
	</fillerSet>
	<fillerSet group="overworld_uncommon" name="corrupted" weight="5">
		<import group="overworld_uncommonOres" name="stone" />
		<filler block="minecraft:stone" weight="5" />
		<filler block="minecraft:cobblestone" weight="1" />
	</fillerSet>
	<fillerSet group="overworld_uncommon" name="cobblestone" weight="1">
		<import group="overworld_uncommonOres" name="stone" />
		<filler block="minecraft:cobblestone" weight="1" />
	</fillerSet>
	<fillerSet group="overworld_uncommon" name="sandNclay" weight="2">
		<import group="overworld_uncommonOres" name="stone" />
		<filler block="minecraft:sandstone" weight="1" />
		<filler block="minecraft:clay" weight="1" />
	</fillerSet>

	<fillerSet group="overworld_uncommonOres" name="stone">
		<import group="overworld_uncommonOres" name="allButVanilla" />
		<filler block="minecraft:redstone_ore" ratio=".01" />
		<filler block="minecraft:gold_ore" ratio=".008" />
		<filler block="minecraft:lapis_ore" ratio=".005" />
	</fillerSet>
	<fillerSet group="overworld_uncommonOres" name="allButVanilla">
		<filler block="IC2:blockOreUran" ratio=".005" mods="IC2,!netherores" />
		<filler block="ImmersiveEngineering:ore" metadata="3" ratio=".03" mods="ImmersiveEngineering" /><!-- Silver -->
		<filler block="ImmersiveEngineering:ore" metadata="4" ratio=".02" mods="ImmersiveEngineering" /><!-- Nickel -->
		<filler block="arsmagica2:vinteumOre" metadata="1" ratio=".01" mods="arsmagica2" /><!-- Chimerite -->
	</fillerSet>


	<!-- rare overworld ores with various base blocks -->
	<fillerSet group="overworld_rare" name="stone" weight="10">
		<import group="overworld_rareOres" name="stone" />
		<filler block="minecraft:stone" weight="100" />
		<filler block="minecraft:iron_ore" weight="5" />
		<filler block="minecraft:lava" weight="1" />
	</fillerSet>
	<fillerSet group="overworld_rare" name="obsidian" weight="2">
		<import group="overworld_rareOres" name="stone" />
		<filler block="minecraft:obsidian" weight="100" />
		<filler block="minecraft:diamond_ore" weight="10" />
		<filler block="minecraft:bedrock" weight="1" />
	</fillerSet>

	<fillerSet group="overworld_rareOres" name="stone">
		<import group="overworld_rareOres" name="allButVanilla" />
		<filler block="minecraft:gold_ore" ratio=".004" />
		<filler block="minecraft:diamond_ore" ratio=".004" />
		<filler block="minecraft:emerald_ore" ratio=".001" />
	</fillerSet>
	<fillerSet group="overworld_rareOres" name="allButVanilla">
		<filler block="IC2:blockOreUran" ratio=".03" mods="IC2,!netherores" />
		<filler block="arsmagica2:vinteumOre" metadata="2" ratio=".01" mods="arsmagica2" /><!-- Blue topaz -->
	</fillerSet>



	<!-- nether ores with simple base block -->
	<fillerSet group="nether" name="stone" weight="10">
		<import group="nether_ores" name="netherrack" />
		<filler block="minecraft:netherrack" weight="100" />
		<filler block="minecraft:lava" weight="5" />
	</fillerSet>

	<fillerSet group="nether_ores" name="netherrack">
		<filler block="minecraft:quartz_ore" ratio="0.1" />
		<filler block="minecraft:glowstone" ratio="0.01" />
		<filler block="minecraft:lava" ratio="0.02" />
		<filler block="arsmagica2:vinteumOre" metadata="4" ratio=".001" mods="arsmagica2" /><!-- Sunstone -->
		<filler block="minecraft:bedrock" ratio=".001" />
	</fillerSet>



	<!-- end ores with simple base block -->
	<fillerSet group="end" name="end" weight="10">
		<import group="end_ores" name="endstone" />
		<filler block="minecraft:netherrack" weight="100" />
		<filler block="minecraft:lava" weight="5" />
	</fillerSet>

	<fillerSet group="end_ores" name="endstone">
		<filler block="arsmagica2:vinteumOre" metadata="3" ratio=".001" mods="arsmagica2" /><!-- Moonstone -->
		<filler block="ae2:quartz" ratio=".0013" mods="appliedenergistics2" />
		<filler block="WarpDrive:blockIridium" ratio=".0001" mods="!netherores" />
	</fillerSet>



	<!-- assorted overworld surface blocks -->
	<fillerSet group="overworld_surface" name="stone" weight="75">
		<filler block="minecraft:stone" weight="100" />
	</fillerSet>
	<fillerSet group="overworld_surface" name="cobblestone" weight="45">
		<filler block="minecraft:stone" weight="100" />
		<filler block="minecraft:cobblestone" weight="20" />
	</fillerSet>
	<fillerSet group="overworld_surface" name="dirt" weight="20">
		<filler block="minecraft:dirt" weight="100" />
	</fillerSet>
	<fillerSet group="overworld_surface" name="ice" weight="30">
		<filler block="minecraft:packed_ice" weight="100" />
		<filler block="minecraft:ice" weight="20" />
	</fillerSet>
	<for variable="metadata" from="0" to="15">
		<fillerSet group="overworld_surface" name="stainedClay_%metadata%" weight="5">
			<filler block="minecraft:stained_hardened_clay" metadata="%metadata%" weight="100" />
		</fillerSet>
	</for>
	<fillerSet group="overworld_surface" name="hardenedClay" weight="5">
		<filler block="minecraft:hardened_clay" weight="100" />
	</fillerSet>
	<fillerSet group="overworld_surface" name="sandy" weight="10"><!-- close color to endstone -->
		<filler block="minecraft:sandstone" weight="100" />
	</fillerSet>



	<!-- assorted nether surface blocks -->
	<fillerSet group="nether_surface" name="netherrack" weight="50">
		<filler block="minecraft:netherrack" weight="100" />
	</fillerSet>
	<fillerSet group="nether_surface" name="quartz" weight="50">
		<filler block="minecraft:netherrack" weight="100" />
		<filler block="minecraft:quartz_ore" weight="2" />
	</fillerSet>
	<for variable="metadata" in="1,6,14">
		<fillerSet group="nether_surface" name="stainedClay_%metadata%" weight="15">
			<filler block="minecraft:stained_hardened_clay" metadata="%metadata%" weight="5" />
		</fillerSet>
	</for>
    <fillerSet group="nether_surface" name="soulsand" weight="20">
        <filler block="minecraft:soul_sand" weight="100" />
    </fillerSet>



	<!-- assorted end surface blocks -->
	<fillerSet group="end_surface" name="endstone" weight="50">
		<filler block="minecraft:end_stone" weight="100" />
	</fillerSet>
	<fillerSet group="end_surface" name="obsiend" weight="50">
		<filler block="minecraft:end_stone" weight="100" />
		<filler block="minecraft:obsidian" weight="15" />
	</fillerSet>
	<for variable="metadata" in="0,4">
		<fillerSet group="end_surface" name="stainedClay_%metadata%" weight="15">
			<filler block="minecraft:stained_hardened_clay" metadata="%metadata%" weight="100" />
		</fillerSet>
	</for>
	<fillerSet group="end_surface" name="clay" weight="15">
		<filler block="minecraft:clay" weight="100" />
	</fillerSet>
	<fillerSet group="end_surface" name="sandy" weight="15">
		<filler block="minecraft:sandstone" weight="100" />
	</fillerSet>



	<!-- WarpDrive gases -->
	<for variable="gasMetadata" in="0,1,2,3,4,5,6,7,8,9,10,11">
		<fillerSet group="gas" name="wd_%gasMetadata%" weight="1">
			<filler block="WarpDrive:blockGas" metadata="%gasMetadata%" weight="100" />
		</fillerSet>
	</for>



    <!-- flow variation for moons -->
    <fillerSet group="moon.flow" name="lava" weight="5">
